/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.TelasRecepcionista;

import View.TelasGerais.Login;
import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author sousa
 */
public class MenuRecepcionista extends javax.swing.JFrame {

    /**
     * Creates new form MenuRecepcionista
     */
    public MenuRecepcionista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLblVoltar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jBtnFEcharEstadia = new javax.swing.JButton();
        jBtnConsultarReserva = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jBtnConsultarHospede = new javax.swing.JButton();
        jBtnExcluirHospede = new javax.swing.JButton();
        jBtnReservarQuarto = new javax.swing.JButton();
        jBtnConsultarQuarto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLblLogo = new javax.swing.JLabel();
        jLblFechar = new javax.swing.JLabel();
        jLblMinimizar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane2.setOpaque(false);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPanel3.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 520, 440));

        jLblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/reply (1).png"))); // NOI18N
        jLblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblVoltarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblVoltarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLblVoltarMouseReleased(evt);
            }
        });
        jPanel3.add(jLblVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 40, 30));

        jPanel4.setBackground(new java.awt.Color(70, 130, 180));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(70, 130, 180));
        jButton6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Gastos da Estadia");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 150, 30));

        jBtnFEcharEstadia.setBackground(new java.awt.Color(70, 130, 180));
        jBtnFEcharEstadia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnFEcharEstadia.setForeground(new java.awt.Color(255, 255, 255));
        jBtnFEcharEstadia.setText("Fechar Estadia");
        jBtnFEcharEstadia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFEcharEstadiaActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnFEcharEstadia, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 150, -1));

        jBtnConsultarReserva.setBackground(new java.awt.Color(70, 130, 180));
        jBtnConsultarReserva.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnConsultarReserva.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConsultarReserva.setText("Consultar Reservas");
        jBtnConsultarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarReservaActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnConsultarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, 50));

        jButton7.setBackground(new java.awt.Color(70, 130, 180));
        jButton7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Cadastrar Hóspede");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 150, -1));

        jBtnConsultarHospede.setBackground(new java.awt.Color(70, 130, 180));
        jBtnConsultarHospede.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnConsultarHospede.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConsultarHospede.setText("Consultar Hóspede");
        jBtnConsultarHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarHospedeActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnConsultarHospede, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 30));

        jBtnExcluirHospede.setBackground(new java.awt.Color(70, 130, 180));
        jBtnExcluirHospede.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnExcluirHospede.setForeground(new java.awt.Color(255, 255, 255));
        jBtnExcluirHospede.setText("Excluir Hóspede");
        jBtnExcluirHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirHospedeActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnExcluirHospede, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 130, 50));

        jBtnReservarQuarto.setBackground(new java.awt.Color(70, 130, 180));
        jBtnReservarQuarto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnReservarQuarto.setForeground(new java.awt.Color(255, 255, 255));
        jBtnReservarQuarto.setText("Reservar Quartos");
        jBtnReservarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReservarQuartoActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnReservarQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 150, 30));

        jBtnConsultarQuarto.setBackground(new java.awt.Color(70, 130, 180));
        jBtnConsultarQuarto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnConsultarQuarto.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConsultarQuarto.setText("Consultar Quartos");
        jBtnConsultarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultarQuartoActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnConsultarQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 150, -1));

        jLabel7.setFont(new java.awt.Font("SUNN", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hóspede:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 40));

        jLabel8.setFont(new java.awt.Font("SUNN", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quartos e reservas");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, 20));

        jLabel9.setFont(new java.awt.Font("SUNN", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estadias:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, 20));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 840, 70));

        jLabel4.setFont(new java.awt.Font("SUNN", 1, 52)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Recepcionista");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        jPanel5.setBackground(new java.awt.Color(70, 130, 180));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblLogo.setFont(new java.awt.Font("SUNN", 1, 24)); // NOI18N
        jLblLogo.setForeground(new java.awt.Color(255, 255, 255));
        jLblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/star.png"))); // NOI18N
        jLblLogo.setText("Hotel");
        jPanel5.add(jLblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLblFechar.setFont(new java.awt.Font("SUNN", 1, 36)); // NOI18N
        jLblFechar.setForeground(new java.awt.Color(255, 255, 255));
        jLblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/x.png"))); // NOI18N
        jLblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblFecharMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblFecharMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLblFecharMouseReleased(evt);
            }
        });
        jPanel5.add(jLblFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 30, 30));

        jLblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/minus.png"))); // NOI18N
        jLblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblMinimizarMouseClicked(evt);
            }
        });
        jPanel5.add(jLblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 30, 30));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/painel.png"))); // NOI18N
        jLabel5.setText("jLabel2");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 690, 530));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/265-swimming-pool-22-hotel-barcelo-costa-cancun_tcm7-126728.jpg"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 840, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblVoltarMouseClicked
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLblVoltarMouseClicked

    private void jLblVoltarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblVoltarMousePressed
        // TODO add your handling code here:
        jLblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/reply (2).png")));
    }//GEN-LAST:event_jLblVoltarMousePressed

    private void jLblVoltarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblVoltarMouseReleased
        // TODO add your handling code here:
        jLblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/reply (1).png")));
    }//GEN-LAST:event_jLblVoltarMouseReleased

    private void jLblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblFecharMouseClicked
        // TODO add your handling code here:
        dispose();
        jLblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/x vermelho.png")));
    }//GEN-LAST:event_jLblFecharMouseClicked

    private void jLblFecharMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblFecharMousePressed
        // TODO add your handling code here:
        jLblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/x vermelho.png")));
    }//GEN-LAST:event_jLblFecharMousePressed

    private void jLblFecharMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblFecharMouseReleased
        // TODO add your handling code here:
        jLblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/x.png")));
    }//GEN-LAST:event_jLblFecharMouseReleased

    private void jLblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblMinimizarMouseClicked
        // TODO add your handling code here:
        Login l = new Login ();
        l.setState(Login.ICONIFIED);
    }//GEN-LAST:event_jLblMinimizarMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        CadastroHospede ch = new CadastroHospede();
        jDesktopPane2.add(ch);
        ((BasicInternalFrameUI)ch.getUI()).setNorthPane(null);
        ch.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jBtnConsultarHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarHospedeActionPerformed
        // TODO add your handling code here:
        ConsultarHospede ch = new ConsultarHospede();
        ch.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnConsultarHospedeActionPerformed

    private void jBtnExcluirHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirHospedeActionPerformed
        // TODO add your handling code here:
        ExcluirHospede eh = new ExcluirHospede();
        eh.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnExcluirHospedeActionPerformed

    private void jBtnConsultarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarQuartoActionPerformed
        // TODO add your handling code here:
        ConsultarQuarto eh = new ConsultarQuarto();
        eh.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnConsultarQuartoActionPerformed

    private void jBtnReservarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReservarQuartoActionPerformed
        // TODO add your handling code here:
        ReservarQuarto eh = new ReservarQuarto();
        eh.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnReservarQuartoActionPerformed

    private void jBtnConsultarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultarReservaActionPerformed
        // TODO add your handling code here:
        ConsultarReserva eh = new ConsultarReserva();
        eh.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnConsultarReservaActionPerformed

    private void jBtnFEcharEstadiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFEcharEstadiaActionPerformed
        // TODO add your handling code here:
        FecharEstadia eh = new FecharEstadia();
        eh.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnFEcharEstadiaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRecepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConsultarHospede;
    private javax.swing.JButton jBtnConsultarQuarto;
    private javax.swing.JButton jBtnConsultarReserva;
    private javax.swing.JButton jBtnExcluirHospede;
    private javax.swing.JButton jBtnFEcharEstadia;
    private javax.swing.JButton jBtnReservarQuarto;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblFechar;
    private javax.swing.JLabel jLblLogo;
    private javax.swing.JLabel jLblMinimizar;
    private javax.swing.JLabel jLblVoltar;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
