/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.TelasGerente;

import View.TelasRecepcionista.MenuRecepcionista;
import com.placeholder.PlaceHolder;
import conexao.ConnectionFactory;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Hospede;
import model.dao.HospedeDAO;

/**
 *
 * @author sousa
 */
public class EditarHospede extends javax.swing.JFrame {

    /**
     * Creates new form EditarHospede
     */
    PlaceHolder texto;

    public EditarHospede() {
        initComponents();
        listarHosp();
        texto = new PlaceHolder(jTextField1, "Nome");
        texto = new PlaceHolder(jTextField9, "Email");
        texto = new PlaceHolder(jTextField11, "Cpf");
        texto = new PlaceHolder(jTextField14, "Telefone");
        texto = new PlaceHolder(jTextField15, "Login");
        texto = new PlaceHolder(jTextField16, "Senha");

        texto = new PlaceHolder(jTextField10, "Nome do Hóspede");
        texto = new PlaceHolder(jTextField12, "Nome do Hóspede");

    }

    public void listarHosp() {
        DefaultTableModel tabela = (DefaultTableModel) jTable4.getModel();
        HospedeDAO hDAO = new HospedeDAO();

        for (Hospede h : hDAO.listar()) {
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");

            tabela.addRow(new Object[]{
                h.getId(),
                h.getNome(),
                h.getEmail(),
                h.getCpf(),
                h.getTelefone(),
                h.getLogin(),
                h.getSenha()

            });
        }
    }

    public void excluir() {
        Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        try {
            stmt = con.prepareStatement("DELETE from tabelaclientes where id = ?");
            int setar = jTable4.getSelectedRow();
            Object valor = jTable4.getModel().getValueAt(setar, 0).toString();
            stmt.setString(1, (String) valor);
            int add = stmt.executeUpdate();

            if (add > 0) {
                JOptionPane.showMessageDialog(null, "Hóspede removido com sucesso");
                MenuGerente tg = new MenuGerente();
                tg.setVisible(true);
                dispose();

            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void setar_texto() {
        PreparedStatement stmt = null;
        ResultSet rs = null;
        Connection con = ConnectionFactory.getConnection();

        try {
            stmt = con.prepareStatement("select nome, email, cpf, telefone, login, senha from tabelaclientes where id = ?");

            int setar = jTable4.getSelectedRow();
            Object valor = jTable4.getModel().getValueAt(setar, 0).toString();
            stmt.setString(1, (String) valor);

            rs = stmt.executeQuery();

            if (rs.next()) {

                jTextField1.setText(rs.getString("nome"));
                jTextField9.setText(rs.getString("email"));
                jTextField11.setText(rs.getString("cpf"));
                jTextField14.setText(rs.getString("telefone"));
                jTextField15.setText(rs.getString("login"));
                jTextField16.setText(rs.getString("senha"));

            }

        } catch (Exception e) {
            System.out.println(e);
        } finally {
            ConnectionFactory.closeConnection(con, stmt, rs);
        }

    }

    public void editar() {
        Hospede h = new Hospede();
        HospedeDAO hdao = new HospedeDAO();

        h.setNome(jTextField1.getText());
        h.setEmail(jTextField9.getText());
        h.setCpf(jTextField11.getText());
        h.setTelefone(jTextField14.getText());
        h.setLogin(jTextField15.getText());
        h.setSenha(jTextField16.getText());

        int setar = jTable4.getSelectedRow();
        Object valor = jTable4.getModel().getValueAt(setar, 0);
        h.setId((int) valor);
        hdao.editar(h);
        MenuGerente r = new MenuGerente();
        r.setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLblLogo2 = new javax.swing.JLabel();
        jLblFechar = new javax.swing.JLabel();
        jLblMinimizar = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLblVoltar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel8.setPreferredSize(new java.awt.Dimension(840, 591));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(144, 238, 144));
        jButton6.setFont(new java.awt.Font("SUNN", 0, 26)); // NOI18N
        jButton6.setText("Selecionar Reserva");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 150, -1));

        jButton5.setBackground(new java.awt.Color(204, 0, 0));
        jButton5.setFont(new java.awt.Font("SUNN", 0, 26)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 130, -1));

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 190, 40));

        jButton3.setBackground(new java.awt.Color(144, 238, 144));
        jButton3.setFont(new java.awt.Font("SUNN", 0, 26)); // NOI18N
        jButton3.setText("Consultar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 120, -1));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 280, 40));

        jLabel11.setFont(new java.awt.Font("SUNN", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Editar Hóspede");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jTable4.setBackground(new java.awt.Color(176, 224, 230));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Email", "cpf", "Telefone", "Login", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setResizable(false);
            jTable4.getColumnModel().getColumn(1).setResizable(false);
            jTable4.getColumnModel().getColumn(2).setResizable(false);
            jTable4.getColumnModel().getColumn(3).setResizable(false);
            jTable4.getColumnModel().getColumn(4).setResizable(false);
            jTable4.getColumnModel().getColumn(5).setResizable(false);
            jTable4.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 610, 110));

        jTextField1.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel8.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 160, 30));

        jButton7.setBackground(new java.awt.Color(144, 238, 144));
        jButton7.setFont(new java.awt.Font("SUNN", 0, 26)); // NOI18N
        jButton7.setText("Alterar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, 130, -1));

        jPanel9.setBackground(new java.awt.Color(70, 130, 180));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblLogo2.setFont(new java.awt.Font("SUNN", 1, 24)); // NOI18N
        jLblLogo2.setForeground(new java.awt.Color(255, 255, 255));
        jLblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/star.png"))); // NOI18N
        jLblLogo2.setText("Hotel");
        jPanel9.add(jLblLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLblFechar.setFont(new java.awt.Font("SUNN", 1, 36)); // NOI18N
        jLblFechar.setForeground(new java.awt.Color(255, 255, 255));
        jLblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/x.png"))); // NOI18N
        jLblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblFecharMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblFecharMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLblFecharMouseReleased(evt);
            }
        });
        jPanel9.add(jLblFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 30, 30));

        jLblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/minus.png"))); // NOI18N
        jLblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblMinimizarMouseClicked(evt);
            }
        });
        jPanel9.add(jLblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 30, 30));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jTextField9.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel8.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 160, 30));

        jTextField11.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel8.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 160, 30));

        jTextField14.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel8.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 160, 30));

        jTextField15.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel8.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 160, 30));

        jTextField16.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel8.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 160, 30));

        jLblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/reply (1).png"))); // NOI18N
        jLblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblVoltarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblVoltarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLblVoltarMouseReleased(evt);
            }
        });
        jPanel8.add(jLblVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 60, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/painel.png"))); // NOI18N
        jLabel4.setText("jLabel2");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 670, 560));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/265-swimming-pool-22-hotel-barcelo-costa-cancun_tcm7-126728.jpg"))); // NOI18N
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jLblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblFecharMouseClicked
        // TODO add your handling code here:
        dispose();
        jLblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/x vermelho.png")));
    }//GEN-LAST:event_jLblFecharMouseClicked

    private void jLblFecharMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblFecharMousePressed
        // TODO add your handling code here:
        jLblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/x vermelho.png")));
    }//GEN-LAST:event_jLblFecharMousePressed

    private void jLblFecharMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblFecharMouseReleased
        // TODO add your handling code here:
        jLblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/x.png")));
    }//GEN-LAST:event_jLblFecharMouseReleased

    private void jLblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblMinimizarMouseClicked
        // TODO add your handling code here:
        setar_texto();
    }//GEN-LAST:event_jLblMinimizarMouseClicked

    private void jLblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblVoltarMouseClicked
        // TODO add your handling code here:
        MenuGerente l = new MenuGerente();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLblVoltarMouseClicked

    private void jLblVoltarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblVoltarMousePressed
        // TODO add your handling code here:
        jLblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/reply (2).png")));
    }//GEN-LAST:event_jLblVoltarMousePressed

    private void jLblVoltarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblVoltarMouseReleased
        // TODO add your handling code here:
        jLblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/reply (1).png")));
    }//GEN-LAST:event_jLblVoltarMouseReleased

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable4MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        setar_texto();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        excluir();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        editar();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarHospede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarHospede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarHospede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarHospede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarHospede().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblFechar;
    private javax.swing.JLabel jLblLogo2;
    private javax.swing.JLabel jLblMinimizar;
    private javax.swing.JLabel jLblVoltar;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
