/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.TelasHospede;

import View.TelasGerais.Login;
import View.TelasGerente.MenuGerente;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author sousa
 */
public class MenuHospede extends javax.swing.JFrame {

    /**
     * Creates new form MenuRecepcionista
     */
    public MenuHospede() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLblVoltar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jBtnSolicitarServico = new javax.swing.JButton();
        jBtnListarPromocoes = new javax.swing.JButton();
        jBtnAlugarSalaoFesta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLblLogo = new javax.swing.JLabel();
        jLblFechar = new javax.swing.JLabel();
        jLblMinimizar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane2.setOpaque(false);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPanel3.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 520, 440));

        jLblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/reply (1).png"))); // NOI18N
        jLblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblVoltarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblVoltarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLblVoltarMouseReleased(evt);
            }
        });
        jPanel3.add(jLblVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 40, 30));

        jPanel4.setBackground(new java.awt.Color(70, 130, 180));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnSolicitarServico.setBackground(new java.awt.Color(70, 130, 180));
        jBtnSolicitarServico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnSolicitarServico.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSolicitarServico.setText("Solicitar Serviço");
        jBtnSolicitarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSolicitarServicoActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnSolicitarServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 150, 30));

        jBtnListarPromocoes.setBackground(new java.awt.Color(70, 130, 180));
        jBtnListarPromocoes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnListarPromocoes.setForeground(new java.awt.Color(255, 255, 255));
        jBtnListarPromocoes.setText("Listar Promoções");
        jBtnListarPromocoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnListarPromocoesActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnListarPromocoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 150, 30));

        jBtnAlugarSalaoFesta.setBackground(new java.awt.Color(70, 130, 180));
        jBtnAlugarSalaoFesta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnAlugarSalaoFesta.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAlugarSalaoFesta.setText("Alugar Salão de Festas");
        jBtnAlugarSalaoFesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlugarSalaoFestaActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnAlugarSalaoFesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 170, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 840, 50));

        jLabel6.setFont(new java.awt.Font("SUNN", 1, 52)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hóspede");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, -1));

        jPanel5.setBackground(new java.awt.Color(70, 130, 180));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblLogo.setFont(new java.awt.Font("SUNN", 1, 24)); // NOI18N
        jLblLogo.setForeground(new java.awt.Color(255, 255, 255));
        jLblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/star.png"))); // NOI18N
        jLblLogo.setText("Hotel");
        jPanel5.add(jLblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLblFechar.setFont(new java.awt.Font("SUNN", 1, 36)); // NOI18N
        jLblFechar.setForeground(new java.awt.Color(255, 255, 255));
        jLblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/x.png"))); // NOI18N
        jLblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblFecharMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblFecharMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLblFecharMouseReleased(evt);
            }
        });
        jPanel5.add(jLblFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 30, 30));

        jLblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/minus.png"))); // NOI18N
        jLblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblMinimizarMouseClicked(evt);
            }
        });
        jPanel5.add(jLblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 30, 30));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/painel.png"))); // NOI18N
        jLabel7.setText("jLabel2");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 690, 530));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/265-swimming-pool-22-hotel-barcelo-costa-cancun_tcm7-126728.jpg"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 840, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblVoltarMouseClicked
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLblVoltarMouseClicked

    private void jLblVoltarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblVoltarMousePressed
        // TODO add your handling code here:
        jLblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/reply (2).png")));
    }//GEN-LAST:event_jLblVoltarMousePressed

    private void jLblVoltarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblVoltarMouseReleased
        // TODO add your handling code here:
        jLblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/reply (1).png")));
    }//GEN-LAST:event_jLblVoltarMouseReleased

    private void jLblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblFecharMouseClicked
        // TODO add your handling code here:
        dispose();
        jLblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/x vermelho.png")));
    }//GEN-LAST:event_jLblFecharMouseClicked

    private void jLblFecharMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblFecharMousePressed
        // TODO add your handling code here:
        jLblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/x vermelho.png")));
    }//GEN-LAST:event_jLblFecharMousePressed

    private void jLblFecharMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblFecharMouseReleased
        // TODO add your handling code here:
        jLblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/x.png")));
    }//GEN-LAST:event_jLblFecharMouseReleased

    private void jLblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblMinimizarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLblMinimizarMouseClicked

    private void jBtnAlugarSalaoFestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlugarSalaoFestaActionPerformed
        // TODO add your handling code here:
        AlugarSalaoDeFesta as = new AlugarSalaoDeFesta();
        as.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnAlugarSalaoFestaActionPerformed

    private void jBtnListarPromocoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnListarPromocoesActionPerformed
        // TODO add your handling code here:
        ListaDePromoções eh = new ListaDePromoções();
        eh.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnListarPromocoesActionPerformed

    private void jBtnSolicitarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSolicitarServicoActionPerformed
        // TODO add your handling code here:
        SolicitarServico ch = new SolicitarServico();
        ch.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnSolicitarServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuHospede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuHospede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuHospede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuHospede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuHospede().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlugarSalaoFesta;
    private javax.swing.JButton jBtnListarPromocoes;
    private javax.swing.JButton jBtnSolicitarServico;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLblFechar;
    private javax.swing.JLabel jLblLogo;
    private javax.swing.JLabel jLblMinimizar;
    private javax.swing.JLabel jLblVoltar;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
